FROM python:3.9-slim-buster AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
RUN pip3 install -r requirements.txt

FROM python:3.9-slim-buster
WORKDIR /app
COPY --from=builder /app/ . 
CMD ["python3", "/app/main.py"]